name: Auto-Versioning

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release
    - name: Publish with semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: semantic-release publish
